<?php

namespace Rushing\Popcorn\Laravel\Baking;

use Illuminate\Contracts\Foundation\Application;

/**
 * The build-time membership cache: `root => class-string` for every registry declared on disk.
 *
 * Registry-kernel ticket 73 D3.1. Shape copied deliberately from
 * `Splicewire\Beam\Frame\FrameResourceManifest`, which does the same job one attribute over for
 * `#[ParticleResource]` and whose own docblock calls it *"beam's mirror of Laravel's
 * `bootstrap/cache/packages.php`"*. An opcache-friendly `return [...]` file, written by
 * `popcorn:registries:cache`, removed by `popcorn:registries:clear` and by `optimize:clear`.
 *
 * ## Why GENERATED and not committed
 *
 * The estate has both precedents and they are not doing the same job. `.beam/registry-conformance.json`
 * is a **ratchet** — a burn-down a human reads in a diff, and it is *supposed* to lag the code, which is
 * what ratcheting means (measured: present at 3 of 7 hosts, tracked at 2). **A membership list is a
 * build product**: it must match the code exactly, and a committed one drifts silently the moment
 * anyone adds a package, which would make "the index is stale" a reviewable-but-unenforced state — the
 * same family of defect ticket 73 exists to remove.
 *
 * `bootstrap/cache/` carries Laravel's own `.gitignore` containing `*`, so nothing here is ever
 * committed; every host measured already runs `package:discover` from `post-autoload-dump`, so the
 * regeneration hook this depends on is present and load-bearing.
 *
 * ## ⚠️ `read()` returns null for ABSENT and `[]` for present-but-empty, and the caller must not collapse them
 *
 * This is the same three-state distinction `Rushing\Doctor\Finding::inconclusive()` draws, and the whole
 * safety of the design rests on the caller keeping it: a host that genuinely declares no registries is
 * quiet, and a host whose artifact was never written is LOUD. See
 * {@see \Rushing\Popcorn\Registries\Exceptions\UnbakedRegistryIndex}.
 *
 * Note this is where the shape deliberately DIVERGES from `FrameResourceManifest`, which treats absent
 * as "fall back to a live scan". That fallback is the 14%-of-boot tax D2 refused, and worse, a boot-time
 * scan can kill the process outright — a missing trait is an uncatchable `E_COMPILE_ERROR`, measured
 * killing three `~/Herd` hosts during phase 1. A fallback that fatals at three hosts is not a fallback.
 */
class BakedRegistryManifest
{
    public const COMMAND = 'popcorn:registries:cache';

    public function __construct(private Application $app) {}

    /** Absolute path, alongside Laravel's own bootstrap-cache manifests. */
    public function path(): string
    {
        return $this->app->bootstrapPath('cache/popcorn-registries.php');
    }

    public function exists(): bool
    {
        return is_file($this->path());
    }

    /**
     * The baked map, or **null when the artifact is absent** — which is a different answer from `[]`.
     *
     * @return array<string, array{class: class-string, by: string}>|null
     */
    public function read(): ?array
    {
        if (! $this->exists()) {
            return null;
        }

        $baked = require $this->path();

        return is_array($baked) ? $baked : [];
    }

    /**
     * @param  array<string, array{class: class-string, by: string}>  $map
     */
    public function write(array $map): void
    {
        ksort($map);

        $rows = [];

        foreach ($map as $root => $entry) {
            $rows[] = sprintf(
                "    %s => ['class' => %s, 'by' => %s],",
                var_export((string) $root, true),
                var_export($entry['class'], true),
                var_export($entry['by'], true),
            );
        }

        $body = "<?php\n\n// Generated by `".self::COMMAND."` — do not edit, do not commit.\n"
            ."// Remove with `popcorn:registries:clear` or `optimize:clear`.\n\nreturn [\n"
            .implode("\n", $rows)
            .($rows === [] ? '' : "\n")
            ."];\n";

        @mkdir(dirname($this->path()), 0755, true);

        file_put_contents($this->path(), $body);
    }

    public function clear(): void
    {
        if ($this->exists()) {
            @unlink($this->path());
        }
    }
}
